### ISSUE TITLE
—exclude examples

### ISSUE THREAD

**Issue by mariomaz87** [geerlingguy/rpi-clone#11]
Hi, I’m reading the documentation but I don’t understand the usage of the exclude command. I want to exclude some folders from a clone, but how can I select them? I’m familiar with rclone —exclude but in this case I would have also to specificy the partition and I don’t know how. Thanks!

**Comment by fmarzocca** [comment]
Maybe I didn't understand your problem, but this is how I am dealing with excluding folders:

`rpi-clone sda -u --exclude=/home/john/myfolder`

**Comment by mariomaz87** [comment]
> Maybe I didn't understand your problem, but this is how I am dealing with excluding folders:
> 
> `rpi-clone sda -u --exclude=/home/john/myfolder`

Thanks. This answer my problem :)

**Comment by framps** [comment]
> This answer my problem :)

Great. But please close this issue now :wink
