### ISSUE TITLE
Maybe set up a little GitHub Pages site with simple instructions?

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/rpi-clone#3]
It could be nice to have a little separate site that is managed via GitHub Pages (with the source in this repo) for documentation. Otherwise (and maybe additionally), the README can be reorganized a little to focus on the use case for most users: clone project and install, then clone internal microSD to another volume.

**Comment by framps** [comment]
Sure. Would be great to document the rpi-clone capabilities from a user point of view. We also should use the GH Pages URL as the landing URL whenever we refer to rpi-clone.

**Comment by geerlingguy** [comment]
I have it set up with a Jekyll install inside `docs`, but it seems to be pulling from the main README and not from the Jekyll setup I have running... have to figure out how the github actions workflow runs...

**Comment by geerlingguy** [comment]
Well, it's there now! Goal is to make it so people can go from 0-100 quickly.

Maybe we could add in a `curl | sudo bash` install script too, so it's a one-click install... I don't always like those but they sure are convenient.

Closing this issue for the time being.
