### ISSUE TITLE
Error cloning to /dev/nvme0n1p1

### ISSUE THREAD

**Issue by kf6spf** [geerlingguy/rpi-clone#40]
I've been using rip-clone for years. Great software!

I've recently been updating my devices to use NVMe M.2 drives. This works fine on Pi 4b, which sees the drive as /dev/sdb, but on the Pi 5, it sees the drive as /dev/nvme0n1, which seems to confuse the partitioning segment. It wants to make /dev/nvme0n11 not /dev/nvme0n1p1 and the same for p2 (wants n12).

I haven't find a way around this yet.

Is there a workaround or is a patch the the software needed?

**Comment by framps** [comment]
> s there a workaround or is a patch the the software needed?

Do you use the current version of rpi-clone from **this** repo?

**Comment by kf6spf** [comment]
Ah. I've been using the original tree. Upgraded and NVMe works fine. Thanks!

Michael

----------------------------------------------------------------------
Michael Wallis     kf6spf     (408) 396-9037      ***@***.***

**Comment by framps** [comment]
Great it works now. Please close this issue now :wink:
